CREATE DATABASE RECEPCIONVEHICULO;
USE RECEPCIONVEHICULO;

CREATE TABLE CLIENTE
(
	CI INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    TELEFONO INTEGER NOT NULL
);

CREATE TABLE RECEPCIONISTA
(
	CI INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE VEHICULO 
(
	PLACA VARCHAR(7) NOT NULL PRIMARY KEY,
    MARCA VARCHAR(50),
    MODELO VARCHAR(50),
    AÑO INTEGER NOT NULL
);

CREATE TABLE FALLA
(
	ID INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
);

CREATE TABLE NOTARECEPCION
(
	NRO INTEGER NOT NULL PRIMARY KEY,
    FECHA DATE NOT NULL,
    HORA DATETIME NOT NULL,
    CI INTEGER NOT NULL,
    
    FOREIGN KEY (CI) 
		REFERENCES CLIENTE(CI)
        ON UPDATE CASCADE
        ON DELETE CASCADE
	
);