CREATE DATABASE ARBOLG2025;
USE ARBOLG2025;
CREATE TABLE PERSONA
(
	ID INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    SEXO CHAR NOT NULL,
    IDPADRE INTEGER,
    IDMADRE INTEGER,
    FOREIGN KEY (IDPADRE)
		REFERENCES PERSONA(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
	FOREIGN KEY (IDMADRE)
		REFERENCES PERSONA(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

INSERT INTO PERSONA VALUES(1, 'JOAQUIN CHUMACERO', 'M', NULL, NULL);
INSERT INTO PERSONA VALUES(2, 'FABIANA CANAVIRI', 'F', NULL, NULL);
INSERT INTO PERSONA VALUES(3, 'PEDRO CHUMACERO CANAVIRI', 'M', 1, 2);
INSERT INTO PERSONA VALUES(4, 'MARIA COLQUE', 'F', NULL, NULL);
INSERT INTO PERSONA VALUES(5, 'JOAQUIN CHUMACERO COLQUE', 'M', 3, 4);
INSERT INTO PERSONA VALUES(6, 'PATRICIA AGUILERA', 'F', NULL, NULL);
INSERT INTO PERSONA VALUES(7, 'JOAQUIN JR CHUMACERO AGUILERA', 'M', 5, 6);
INSERT INTO PERSONA VALUES(8, 'CARLA MARIA CHUMACERO AGUILERA', 'F', 5, 6);	
INSERT INTO PERSONA VALUES(9, 'CARLA PEREZ', 'F', NULL, NULL);
INSERT INTO PERSONA VALUES(10, 'SANTIAGO CHUMACERO PEREZ', 'M', 5, 9);

-- Mostrar el ID Y NOMBRE del padre de JOAQUIN CHUMACERO COLQUE
SELECT PADRE.ID, PADRE.NOMBRE
FROM PERSONA HIJO, PERSONA PADRE
WHERE HIJO.IDPADRE = PADRE.ID
AND HIJO.NOMBRE = 'JOAQUIN CHUMACERO COLQUE';

SELECT ID, NOMBRE
FROM PERSONA
WHERE ID IN
(
	SELECT IDPADRE
	FROM PERSONA
	WHERE PERSONA.NOMBRE = 'JOAQUIN CHUMACERO COLQUE'
);

-- Mostrar el ID Y NOMBRE DE LOS HIJOS DE JOAQUIN CHUMACERO COLQUE
SELECT HIJO.ID, HIJO.NOMBRE
FROM PERSONA HIJO, PERSONA PADRE
WHERE HIJO.IDPADRE = PADRE.ID
AND PADRE.NOMBRE = 'JOAQUIN CHUMACERO COLQUE';

SELECT ID , NOMBRE
FROM PERSONA
WHERE PERSONA.IDPADRE IN
(
	SELECT ID
	FROM PERSONA
    WHERE PERSONA.NOMBRE = 'JOAQUIN CHUMACERO COLQUE'
);
					 
-- Mostrar LOS NIETOS DE PEDRO CHUMACERO CANAVIRI
SELECT HIJO.ID, HIJO.NOMBRE
FROM PERSONA ABUELO, PERSONA PADRE, PERSONA HIJO
WHERE HIJO.IDPADRE = PADRE.ID
AND PADRE.IDPADRE = ABUELO.ID
AND ABUELO.NOMBRE = 'PEDRO CHUMACERO CANAVIRI';

-- anidada
SELECT ID, NOMBRE FROM PERSONA
WHERE IDPADRE IN
(
	SELECT ID FROM PERSONA
    WHERE IDPADRE IN
    (
		SELECT ID FROM PERSONA
        WHERE NOMBRE = 'PEDRO CHUMACERO CANAVIRI'
	)
);

-- Mostrar Con quienes tuvo hijos JOAQUIN CHUMACERO COLQUE (MADRES)
SELECT DISTINCT MADRE.ID, MADRE.NOMBRE
FROM PERSONA MADRE, PERSONA HIJO, PERSONA PADRE
WHERE HIJO.IDMADRE = MADRE.ID 
AND HIJO.IDPADRE = PADRE.ID
AND PADRE.NOMBRE = 'JOAQUIN CHUMACERO COLQUE';

SELECT ID, NOMBRE FROM PERSONA
WHERE ID IN
(
	SELECT IDMADRE FROM PERSONA
    WHERE IDPADRE IN
	(
		SELECT ID FROM PERSONA
        WHERE NOMBRE = 'JOAQUIN CHUMACERO COLQUE'
	)
);

SELECT * FROM PERSONA;